### ISSUE TITLE
SPA url tracking

### ISSUE THREAD

**Issue by Ku3mi41** [dugwood/clickheat#11]
Presently script track only base url without hash (#viewName?someParam=false), but in singlepage applications viewName is main concept and must be tracked like a part of url adress for correct heatmap background.
Hash can't be getted at server side, so it must be passed throw client side parameter, and then writed in url.txt.
So, if you think it's a reasonable feature I can make pull request.

**Comment by dugwood** [comment]
Thanks @Ku3mi41 for the proposal. So far I don't think it's an essential feature, as you can do it with a little skills in the Javascript code to paste on your pages, for example:
`clickHeatGroup = encodeURIComponent(window.location.pathname+window.location.search+window.location.hash.replace('#', ''));`
or only the hash:
`clickHeatGroup = encodeURIComponent(window.location.hash.replace('#', ''));`
Don't forget to change `clickHeatQuota = -1` (it's the default, but it may be already set to 3 in the copy-paste code), so that you can track all clicks, as you don't change page.
