### ISSUE TITLE
Write Permission error on installation

### ISSUE THREAD

**Issue by fusillijerry89** [dugwood/clickheat#16]
I am getting this message when I visit /clickheat/index.php

Write permissions in configuration directory(C:/Users/xxx/Dev/wamp64/www/clickheat/config/) |   |  
-- | -- | --
GD graphic library |   |  
Next step: configuration

**Comment by dugwood** [comment]
@fusillijerry89 do you see any error? You've pasted images that were removed, hence I don't know if it was a yes/no image.

If you have access to the next step, that usual means everything is in order :-)

**Comment by username1290** [comment]
Seeing same text as @fusillijerry89 
Folders aren't being created on first run, manually created them but config/ seems to be sketchy, 

btw **Next step** is just text, not a button.

What are the permissions needed?

tried running chgrp and chmod but my sudo powers failed me.

**Comment by username1290** [comment]
Tried 000webhost.com, same thing, doesn't work.
Using OpenShift, it advances to the next screen, but on Check Configuration, **logs** folder got throws this message:


```
( ! ) Warning: fopen(/opt/app-root/src/logs/test.txt): failed to open stream: No such file or directory in /opt/app-root/src/config.php on line 335
--


1 | 0.0001 | 264512 | {main}( ) | ../index.php:0
2 | 0.0009 | 294944 | include( '/opt/app-root/src/config.php') | ../index.php:199
3 | 0.0012 | 302608 | fopen ( ) | ../config.php:335



```


`Logfiles directory doesn't have write permissions, please give it write permission for PHP user`

**Comment by dugwood** [comment]
I don't know how it's possible that you get a `No such file or directory` here:
https://github.com/dugwood/clickheat/blob/master/config.php#L335

=> it can't be reached without the logs directory. Hence you may not have write permissions on logs/ directory.

You just need write permissions, for the user that runs the script, and it may depend on what solution you're using (fast-cgi, php-fpm...). What is the user running the script? It may not be the same as the user you use to upload files!

Try to dump the user in config.php, by adding `var_dump($_SERVER);exit;` in the beginning of the file (after `<?php` marker).

**Comment by dugwood** [comment]
`Next step` is not clickable as you have an error. Going further would only raise more errors.

**Comment by username1290** [comment]
FYI got it working on OpenShift, manually created a *logs* folder. 
What providers or VM do you recommend?

**Comment by dugwood** [comment]
Had a lot of issues with PHP safe mode back in the days... But now the only issue would be the user you use for FTP and the user which runs your PHP code.

Sometimes creating the folder through PHP is the right call, sometimes it's better to do it with FTP. The real issue is the host provider, as they use various users, where they should always use the same for both FTP and PHP (or at least 2 users with common group, so these can read/write the same files/directories).

I don't recommend any providers, as many work correctly with file permissions. Or most of the time, you have a FAQ to help you with it. There's too much providers out there to write something about write permissions :-)

But it most cases:
 - same user (FTP/PHP) and write permission: no issue
 - different users, both have write permission: no issue
 - different users, one can't write into other's files: issue

When you have such an issue, there's also temporary directories, where users can read/write with their own permissions. This can be another option to consider (and the `logs/` directory will be in another directory than ClickHeat).

I'll mark this closed as it's a hosting issue.

**Comment by username1290** [comment]
Sure, thanks
